version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-app
    container_name: web-app
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    links:
      - db
      - redis
  db:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-db
    container_name: web-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports:
      - "5432:5432"
  redis:
    image: redis:4.0-alpine
    container_name: web-redis
    ports:
      - "6379:6379"
  mongodb:
    image: mongo:4.0
    container_name: web-mongo
    ports:
      - "27017:27017"